CREATE TABLE "MType" (
    "ID" INTEGER NOT NULL CONSTRAINT "PK_MType" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NULL
);

CREATE TABLE "MUnit" (
    "ID" INTEGER NOT NULL CONSTRAINT "PK_MUnit" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NULL
);

CREATE TABLE "MValue" (
    "ID" INTEGER NOT NULL CONSTRAINT "PK_MValue" PRIMARY KEY AUTOINCREMENT,
    "TypeID" INTEGER NOT NULL,
    "Value" REAL NOT NULL,
    "UnitID" INTEGER NOT NULL,
    "RecordTime" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "FK_MValue_MType_TypeID" FOREIGN KEY ("TypeID") REFERENCES "MType" ("ID") ON DELETE SET NULL,
    CONSTRAINT "FK_MValue_MUnit_UnitID" FOREIGN KEY ("UnitID") REFERENCES "MUnit" ("ID") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_MType_Name" ON "MType" ("Name");

CREATE UNIQUE INDEX "IX_MUnit_Name" ON "MUnit" ("Name");

CREATE INDEX "IX_MValue_TypeID" ON "MValue" ("TypeID");

CREATE INDEX "IX_MValue_UnitID" ON "MValue" ("UnitID");
