CREATE TABLE IF NOT EXISTS "MUnit" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MUnit_Name" ON "MUnit" (
	"Name"
);
CREATE TABLE IF NOT EXISTS "MType" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MType_Name" ON "MType" (
	"Name"
);
CREATE TABLE IF NOT EXISTS "MLocation" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MLocation_Name" ON "MLocation" (
	"Name"
);
CREATE TABLE IF NOT EXISTS "MValue" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"TypeID"	INTEGER NOT NULL,
	"LocationID"	INTEGER NOT NULL,
	"Value"	REAL NOT NULL,
	"UnitID"	INTEGER NOT NULL,
	"RecordTime"	TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT "FK_MValue_MLocation_LocationID" FOREIGN KEY("LocationID") REFERENCES "MLocation"("ID") ON DELETE SET NULL,
	CONSTRAINT "FK_MValue_MType_TypeID" FOREIGN KEY("TypeID") REFERENCES "MType"("ID") ON DELETE SET NULL,
	CONSTRAINT "FK_MValue_MUnit_UnitID" FOREIGN KEY("UnitID") REFERENCES "MUnit"("ID") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_MValue_UnitID" ON "MValue" (
	"UnitID"
);
CREATE INDEX IF NOT EXISTS "IX_MValue_TypeID" ON "MValue" (
	"TypeID"
);
CREATE INDEX IF NOT EXISTS "IX_MValue_LocationID" ON "MValue" (
	"LocationID"
);
COMMIT;
